# Generated by Django 3.2 on 2024-10-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=50)),
                ('origenProducto', models.CharField(max_length=50)),
                ('descripcionProducto', models.CharField(max_length=50)),
                ('tipoProducto', models.CharField(max_length=50)),
                ('cantidadProducto', models.IntegerField(max_length=14)),
            ],
        ),
    ]
